export default {
  // [price per kg, plant]
  fertilizer: {
    Urea: [35, ["Corn", "Sunflower"]],
    AN: [38, ["Corn"]],
    KAN: [37, ["Corn"]],
    "NPK (4:1:2)": [40, ["Corn"]],
    "NPK (20:20:20)": [45, ["Corn"]],
    "NPK (15:15:15)": [32, ["Corn", "Sunflower"]],
    "NPK (16:16:16)": [33, ["Corn", "Sunflower"]],
    "Trace elements (Zn)": [50, ["Corn"]],
    "NPK (8:15:15)": [50, ["Soya", "Sunflower"]],
    "NPK (6:24:12)": [50, ["Soya", "Sunflower"]],
    "NPK (16:27:7)": [50, ["Soya"]],
    "NS (20:24)": [50, ["Soya"]],
    "NP (10:35)": [50, ["Soya", "Sunflower"]],
  },
  sprayer: {
    // [bottle price, array of plants, area of bottle, iuapac]
    "S-metolahlor 1": [1000, ["Corn"], 40, "S-metolahlor"],
    "S-metolahlor 2": [1100, ["Corn"], 50, "S-metolahlor"],
    "S-metolahlor 3": [1200, ["Corn"], 25, "S-metolahlor"],
    "Terbuthylazine 1": [1445, ["Corn"], 40, "Terbuthylazine"],
    "Terbuthylazine 2": [988, ["Corn"], 55, "Terbuthylazine"],
    "Terbuthylazine 3": [752, ["Corn"], 100, "Terbuthylazine"],
    "2,4D 1": [785, ["Corn", "Wheat"], 80, "2,4D"],
    "2,4D 2": [1555, ["Corn", "Wheat"], 40, "2,4D"],
    "Nikosu l Furon 1": [755, ["Corn"], 25, "Nikosu l Furon"],
    "Nikosu l Furon 2": [751, ["Corn"], 40, "Nikosu l Furon"],
    "Nikosu l Furon 3": [752, ["Corn"], 60, "Nikosu l Furon"],

    "Aminopyralid-potassium 355 g/kg + Florasulam 150 g/kg": [
      752,
      ["Wheat"],
      60,
      "Aminopyralid-potassium 355 g/kg + Florasulam 150 g/kg",
    ],
    "Fluksapiroksad 75 g/l + Pyraclostrobin 150 g/l": [
      752,
      ["Wheat"],
      60,
      "Fluksapiroksad 75 g/l + Pyraclostrobin 150 g/l",
    ],
    "Alpha-cypermethrin 100 g/l": [
      752,
      ["Wheat"],
      60,
      "Alpha-cypermethrin 100 g/l",
    ],

    "EC ramp": [752, ["Soya"], 60, "Clomazone"],
    Galbenon: [752, ["Soya"], 60, "Bentazone"],
    Basar: [752, ["Soya", "Sunflower"], 60, "S-metolahlor"],
    "Velton WG": [752, ["Soya"], 60, "Metribuzin"],
    Okvir: [752, ["Soya"], 60, "Tifensulfuron-metil"],
    Rafal: [752, ["Soya", "Sunflower"], 60, "Кletodim"],
    "Globus EC": [752, ["Soya"], 60, "Кvizalopof-P-etil"],

    "Fobos EC": [752, ["Sunflower"], 60, "Bifentrin"],
    Mont: [752, ["Sunflower"], 60, "Bifentrin"],
    Terbis: [752, ["Sunflower"], 60, "Terbuthylazine"],
    Kletox: [752, ["Sunflower"], 60, "Кletodim"],
    Bosco: [752, ["Sunflower"], 60, "Boskalid"],
    Funomil: [752, ["Sunflower"], 60, "Tiofanat-metil"],
  },
  seed: {
    // [bag price, plant]
    "Seeds cheaper (corn)": [3500, "corn"],
    "Seeds medium (corn)": [3800, "corn"],
    "Seeds are more expensive (corn)": [4000, "corn"],
    "Seeds cheaper (wheat)": [1500, "wheat"],
    "Seeds medium (wheat)": [1800, "wheat"],
    "Seeds are more expensive (wheat)": [2000, "wheat"],
    "Seeds cheaper (soya)": [1500, "Soya"],
    "Seeds medium (soya)": [1800, "Soya"],
    "Seeds are more expensive (soya)": [2000, "Soya"],
    "Seeds cheaper (sunflower)": [8000, "Sunflower"],
    "Seeds medium (sunflower)": [10000, "Sunflower"],
    "Seeds are more expensive (sunflower)": [12000, "Sunflower"],
  },
};
